import { db } from "@workspace/db";
import { notifications } from "@workspace/db";

export type NotificationType = "digest" | "badge" | "battle_result" | "streak_risk" | "thread_candidate";

export async function createNotification(params: {
  userId: number;
  type: NotificationType;
  titleKey: string;
  bodyKey: string;
  bodyParams?: Record<string, unknown>;
  payload?: Record<string, unknown>;
  deepLink?: string;
  // Set this for anything generated by a background job that may run
  // concurrently or retry (battle results, streak risk, digests) — the
  // notifications.dedupe_key column has a UNIQUE constraint, so a repeat
  // insert with the same key is silently dropped instead of double-notifying.
  dedupeKey?: string;
}): Promise<void> {
  await db.insert(notifications).values({
    userId: params.userId,
    type: params.type,
    titleKey: params.titleKey,
    bodyKey: params.bodyKey,
    bodyParams: params.bodyParams ?? null,
    payload: params.payload ?? null,
    deepLink: params.deepLink ?? null,
    dedupeKey: params.dedupeKey ?? null,
  }).onConflictDoNothing();
}
