import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import leaderboardRouter from "./leaderboard";
import gamificationRouter from "./gamification";
import recommendationsRouter from "./recommendations";
import chatRouter from "./chat";
import translateRouter from "./translate";
import threadsRouter from "./threads";
import threadCandidatesRouter from "./threadCandidates";
import battlesRouter from "./battles";
import guestBattlesRouter from "./guestBattles";
import adminRouter from "./admin";
import authRouter from "./auth";
import billingRouter from "./billing";
import revenuecatRouter from "./revenuecat";
import notificationsRouter from "./notifications";
import bestPracticesRouter from "./bestPractices";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(usersRouter);
router.use(leaderboardRouter);
router.use(gamificationRouter);
router.use(recommendationsRouter);
router.use(chatRouter);
router.use(translateRouter);
router.use(threadsRouter);
router.use(threadCandidatesRouter);
router.use(battlesRouter);
router.use(guestBattlesRouter);
router.use(adminRouter);
router.use(billingRouter);
router.use(revenuecatRouter);
router.use(notificationsRouter);
router.use(bestPracticesRouter);

export default router;
