import { getAuth } from "@clerk/express";
import { Router } from "express";
import { db } from "@workspace/db";
import { users, threadCandidates, threads } from "@workspace/db";
import { eq, and, desc } from "drizzle-orm";
import { getOrCreateUser } from "../lib/getOrCreateUser";

const router = Router();

// ─── GET /thread-candidates — current user's pending candidates ────────────
router.get("/thread-candidates", async (req, res) => {
  try {
    const clerkId = getAuth(req).userId;
    if (!clerkId) { res.status(401).json({ error: "Unauthorized" }); return; }

    const user = await getOrCreateUser(clerkId);
    if (!user) { res.status(500).json({ error: "Failed to initialize user" }); return; }

    const rows = await db.select().from(threadCandidates)
      .where(and(eq(threadCandidates.userId, user.id), eq(threadCandidates.status, "pending")))
      .orderBy(desc(threadCandidates.createdAt));

    res.json(rows.map(c => ({
      id: c.id,
      question: c.question,
      aiTitle: c.aiTitle,
      description: c.description,
      category: c.category,
      motivationBlurb: c.motivationBlurb,
      metricsSnapshot: c.metricsSnapshot ?? null,
      status: c.status,
      createdAt: c.createdAt,
    })));
  } catch (err) {
    console.error("[thread-candidates] list error", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

// ─── PATCH /thread-candidates/:id — edit before confirming ──────────────────
router.patch("/thread-candidates/:id", async (req, res) => {
  try {
    const clerkId = getAuth(req).userId;
    if (!clerkId) { res.status(401).json({ error: "Unauthorized" }); return; }

    const user = await getOrCreateUser(clerkId);
    if (!user) { res.status(500).json({ error: "Failed to initialize user" }); return; }

    const [candidate] = await db.select().from(threadCandidates)
      .where(and(eq(threadCandidates.id, req.params.id), eq(threadCandidates.userId, user.id)))
      .limit(1);
    if (!candidate) { res.status(404).json({ error: "Candidate not found" }); return; }
    if (candidate.status !== "pending") { res.status(400).json({ error: "Candidate already resolved" }); return; }

    const { question, description, category } = req.body ?? {};
    const updates: Partial<typeof threadCandidates.$inferInsert> = {};
    if (typeof question === "string" && question.trim().length >= 10) updates.question = question.trim().slice(0, 160);
    if (typeof description === "string") updates.description = description.trim().slice(0, 300) || null;
    if (typeof category === "string") updates.category = category;

    const [updated] = await db.update(threadCandidates).set(updates)
      .where(eq(threadCandidates.id, candidate.id))
      .returning();

    res.json({
      id: updated.id,
      question: updated.question,
      aiTitle: updated.aiTitle,
      description: updated.description,
      category: updated.category,
      motivationBlurb: updated.motivationBlurb,
      metricsSnapshot: updated.metricsSnapshot ?? null,
      status: updated.status,
      createdAt: updated.createdAt,
    });
  } catch (err) {
    console.error("[thread-candidates] edit error", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

// ─── POST /thread-candidates/:id/confirm — publish into `threads` ──────────
router.post("/thread-candidates/:id/confirm", async (req, res) => {
  try {
    const clerkId = getAuth(req).userId;
    if (!clerkId) { res.status(401).json({ error: "Unauthorized" }); return; }

    const user = await getOrCreateUser(clerkId);
    if (!user) { res.status(500).json({ error: "Failed to initialize user" }); return; }

    const [candidate] = await db.select().from(threadCandidates)
      .where(and(eq(threadCandidates.id, req.params.id), eq(threadCandidates.userId, user.id)))
      .limit(1);
    if (!candidate) { res.status(404).json({ error: "Candidate not found" }); return; }
    if (candidate.status !== "pending") {
      res.status(400).json({ error: "Candidate already resolved" });
      return;
    }

    const [thread] = await db.insert(threads).values({
      question: candidate.question,
      description: candidate.description,
      category: candidate.category ?? "philosophy",
      createdBy: clerkId,
      isAutoGenerated: true,
    }).returning();

    await db.update(threadCandidates).set({
      status: "confirmed",
      publishedThreadId: thread.id,
      resolvedAt: new Date(),
    }).where(eq(threadCandidates.id, candidate.id));

    res.json({ threadId: thread.id });
  } catch (err) {
    console.error("[thread-candidates] confirm error", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

// ─── POST /thread-candidates/:id/discard — drop it, never publish ──────────
router.post("/thread-candidates/:id/discard", async (req, res) => {
  try {
    const clerkId = getAuth(req).userId;
    if (!clerkId) { res.status(401).json({ error: "Unauthorized" }); return; }

    const user = await getOrCreateUser(clerkId);
    if (!user) { res.status(500).json({ error: "Failed to initialize user" }); return; }

    const [candidate] = await db.select().from(threadCandidates)
      .where(and(eq(threadCandidates.id, req.params.id), eq(threadCandidates.userId, user.id)))
      .limit(1);
    if (!candidate) { res.status(404).json({ error: "Candidate not found" }); return; }
    if (candidate.status !== "pending") {
      res.status(400).json({ error: "Candidate already resolved" });
      return;
    }

    await db.update(threadCandidates).set({
      status: "discarded",
      resolvedAt: new Date(),
    }).where(eq(threadCandidates.id, candidate.id));

    res.json({ ok: true });
  } catch (err) {
    console.error("[thread-candidates] discard error", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
